// de_nust2.res - created with RESGen v2.0 BETA 3.
// RESGen is made by Jeroen "ShadowLord" Bogers.
// For more info go to http://resgen.hltools.com
// or E-mail me at resgen@hltools.com.

// .res entries (46):
gfx/env/embassyup.tga
gfx/env/embassydn.tga
gfx/env/embassylf.tga
gfx/env/embassyrt.tga
gfx/env/embassyft.tga
gfx/env/embassybk.tga
de_nust2.wad
models/de_nust2/gate.mdl
models/de_nust2/fence.mdl
models/de_nust2/kia_wheatley.mdl
models/de_nust2/truck1.mdl
models/de_nust2/fence_up.mdl
models/de_nust2/generator3.mdl
models/de_nust2/fan.mdl
models/de_nust2/fan2.mdl
models/de_nust2/light.mdl
models/de_nust2/wires.mdl
models/de_nust2/worklight.mdl
sprites/de_nust2/light.spr
sprites/de_nust2/flare.spr
models/de_nust2/window.mdl
models/de_nust2/cabinet1.mdl
models/de_nust2/table.mdl
models/de_nust2/chair.mdl
models/de_nust2/pc.mdl
models/de_nust2/light2.mdl
sprites/de_nust2/glow.spr
models/player/gsg9/gsg9.mdl
models/player/leet/leet.mdl
models/de_nust2/building2.mdl
models/de_nust2/vertigo_skybox.mdl
models/de_nust2/barricade1.mdl
models/de_nust2/garbage.mdl
models/de_nust2/electricbox2.mdl
sound/ambience/de_nust2/engine.wav
sound/ambience/de_nust2/voltage.wav
sound/ambience/de_nust2/air.wav
sound/ambience/de_nust2/city.wav
sound/ambience/de_nust2/aircond.wav
sound/ambience/de_nust2/woodlandz.wav
sound/ambience/de_nust2/industrial.wav
sound/ambience/de_nust2/hum.wav
sound/ambience/de_nust2/ambulance.wav
sound/ambience/crtnoise.wav
models/de_nust2/tree2.mdl
models/de_nust2/fading309.mdl
sound/ultimate_sounds/doublekill1_ultimate.wav 
sound/ultimate_sounds/doublekill2_ultimate.wav 
sound/ultimate_sounds/firstblood1_ultimate.wav 
sound/ultimate_sounds/firstblood2_ultimate.wav 
sound/ultimate_sounds/headshot1_ultimate.wav 
sound/ultimate_sounds/headshot2_ultimate.wav 
sound/ultimate_sounds/holyshit_ultimate.wav 
sound/ultimate_sounds/killingspree_ultimate.wav 
sound/ultimate_sounds/knife1_ultimate.wav 
sound/ultimate_sounds/knife2_ultimate.wav 
sound/ultimate_sounds/ludicrouskill_ultimate.wav 
sound/ultimate_sounds/megakill_ultimate.wav 
sound/ultimate_sounds/monsterkill_ultimate.wav 
sound/ultimate_sounds/multikill_ultimate.wav 
sound/ultimate_sounds/nade_ultimate.wav 
sound/ultimate_sounds/prepare1_ultimate.wav 
sound/ultimate_sounds/prepare2_ultimate.wav 
sound/ultimate_sounds/prepare3_ultimate.wav 
sound/ultimate_sounds/rampage_ultimate.wav 
sound/ultimate_sounds/suicide1_ultimate.wav 
sound/ultimate_sounds/suicide2_ultimate.wav 
sound/ultimate_sounds/suicide3_ultimate.wav 
sound/ultimate_sounds/suicide4_ultimate.wav 
sound/ultimate_sounds/triplekill_ultimate.wav 
sound/ultimate_sounds/ultrakill_ultimate.wav 
sound/ultimate_sounds/unstoppable_ultimate.wav 
